"use client";

import * as React from "react";
import { 
  FileText, 
  Search, 
  Trash2, 
  Download, 
  Eye, 
  MoreVertical,
  FileSpreadsheet
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover";
import { Separator } from "@/components/ui/separator";

export default function AdminBiodatas() {
  const [search, setSearch] = React.useState("");
  const [langFilter, setLangFilter] = React.useState("all");

  const biodatas = [
    { id: "B99-1002", name: "Rohan Suresh Mehta", community: "Gujarati", language: "Gujarati", template: "Classic Gold", downloads: 8, date: "2026-05-24" },
    { id: "B99-1001", name: "Anjali Manoj Patil", community: "Maratha", language: "Marathi", template: "Royal Crimson", downloads: 14, date: "2026-05-24" },
    { id: "B99-1000", name: "Karan Avinash Sharma", community: "Brahmin", language: "Hindi", template: "Warm Sand", downloads: 5, date: "2026-05-23" },
    { id: "B99-0999", name: "Nisha Srinivas Iyer", community: "Iyer", language: "English", template: "Deep Teal", downloads: 22, date: "2026-05-23" },
    { id: "B99-0998", name: "Suresh Baliram Giri", community: "Goswami", language: "Hindi", template: "Royal Crimson", downloads: 3, date: "2026-05-22" },
    { id: "B99-0997", name: "Divya Ramesh Shah", community: "Jain", language: "Gujarati", template: "Classic Gold", downloads: 19, date: "2026-05-21" },
    { id: "B99-0996", name: "Rajesh Pandurang Pawar", community: "Maratha", language: "Marathi", template: "Royal Purple", downloads: 11, date: "2026-05-21" },
  ];

  const filtered = biodatas.filter(bio => {
    const matchesSearch = bio.name.toLowerCase().includes(search.toLowerCase()) || bio.id.toLowerCase().includes(search.toLowerCase());
    const matchesLang = langFilter === "all" || bio.language.toLowerCase() === langFilter.toLowerCase();
    return matchesSearch && matchesLang;
  });

  return (
    <div className="space-y-6 text-foreground">
      {/* Title Header */}
      <div>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-foreground tracking-tight flex items-center gap-2">
          <FileText className="w-8 h-8 text-primary" />
          Matrimonial Biodatas
        </h1>
        <p className="text-xs sm:text-sm text-muted-foreground mt-1">
          Review, analyze, and manage biodata documents generated by users.
        </p>
      </div>

      {/* Control bar */}
      <div className="flex flex-col sm:flex-row gap-4 items-center justify-between bg-card p-4 border border-border rounded-xl shadow-sm">
        <div className="relative w-full sm:w-80">
          <Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" />
          <input
            type="search"
            placeholder="Search by ID or name..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-muted/40 border border-border focus:border-primary text-foreground rounded-lg pl-10 pr-3 py-2 text-xs outline-none placeholder:text-muted-foreground transition-all focus:ring-1 focus:ring-primary/30"
          />
        </div>

        <div className="flex items-center gap-3 w-full sm:w-auto justify-end">
          <Select defaultValue="all" onValueChange={(val) => setLangFilter(val || "all")}>
            <SelectTrigger className="w-36 bg-muted/40 border-border text-foreground text-xs h-9 cursor-pointer">
              <SelectValue placeholder="Language" />
            </SelectTrigger>
            <SelectContent className="bg-popover border border-border text-popover-foreground text-xs">
              <SelectItem value="all">All Languages</SelectItem>
              <SelectItem value="english">English</SelectItem>
              <SelectItem value="hindi">Hindi</SelectItem>
              <SelectItem value="marathi">Marathi</SelectItem>
              <SelectItem value="gujarati">Gujarati</SelectItem>
            </SelectContent>
          </Select>
          
          <Button variant="outline" size="sm" className="h-9 bg-muted/20 border-border text-muted-foreground hover:text-foreground text-xs cursor-pointer flex gap-1.5">
            <FileSpreadsheet className="w-3.5 h-3.5" />
            <span>Export CSV</span>
          </Button>
        </div>
      </div>

      {/* Biodata list grid */}
      <Card className="bg-card border border-border rounded-xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-xs">
            <thead>
              <tr className="border-b border-border bg-muted/25 text-muted-foreground font-bold uppercase tracking-wider">
                <th className="p-4">Document ID</th>
                <th className="p-4">Name</th>
                <th className="p-4">Community</th>
                <th className="p-4">Language</th>
                <th className="p-4">Template Name</th>
                <th className="p-4">Downloads</th>
                <th className="p-4">Created Date</th>
                <th className="p-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/30 text-foreground/90">
              {filtered.length > 0 ? (
                filtered.map((bio) => (
                  <tr key={bio.id} className="hover:bg-muted/10 transition-colors">
                    <td className="p-4 font-mono font-bold text-primary">{bio.id}</td>
                    <td className="p-4 font-bold text-foreground">{bio.name}</td>
                    <td className="p-4">{bio.community}</td>
                    <td className="p-4">
                      <span className="bg-muted border border-border text-muted-foreground text-[10px] font-bold px-2 py-0.5 rounded-full">
                        {bio.language}
                      </span>
                    </td>
                    <td className="p-4 text-muted-foreground font-medium">{bio.template}</td>
                    <td className="p-4 text-foreground/90 font-bold">{bio.downloads}</td>
                    <td className="p-4 text-muted-foreground font-medium">{bio.date}</td>
                    <td className="p-4 text-right flex justify-end gap-1.5">
                      <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-foreground hover:bg-muted/50 cursor-pointer">
                        <Eye className="w-3.5 h-3.5" />
                        <span className="sr-only">View</span>
                      </Button>
                      <Button variant="ghost" size="icon" className="h-7 w-7 text-primary hover:bg-primary/10 cursor-pointer">
                        <Download className="w-3.5 h-3.5" />
                        <span className="sr-only">Download</span>
                      </Button>
                      <Popover>
                        <PopoverTrigger
                          render={
                            <Button variant="ghost" size="icon" className="h-7 w-7 text-muted-foreground hover:text-destructive cursor-pointer">
                              <MoreVertical className="w-3.5 h-3.5" />
                            </Button>
                          }
                        />
                        <PopoverContent className="w-40 p-1 border border-border bg-popover text-popover-foreground shadow-2xl rounded-lg">
                          <button className="w-full flex items-center gap-2 px-2.5 py-1.5 rounded hover:bg-muted/50 text-xs text-muted-foreground hover:text-foreground transition-colors cursor-pointer text-left">
                            <span>Lock Document</span>
                          </button>
                          <Separator className="bg-border/50 my-1" />
                          <button className="w-full flex items-center gap-2 px-2.5 py-1.5 rounded hover:bg-destructive/10 text-xs text-muted-foreground hover:text-destructive transition-colors cursor-pointer text-left">
                            <Trash2 className="w-3.5 h-3.5" />
                            <span>Delete</span>
                          </button>
                        </PopoverContent>
                      </Popover>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={8} className="p-8 text-center text-muted-foreground font-bold uppercase tracking-wider">
                    No matching biodata records found.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
